### ISSUE TITLE
Backup Copy Issue

### ISSUE THREAD

**Issue by DoMeLater** [marcohorstmann/MyVeeamReport#19]
There are two options for backup copies.

Immediate copy (mirroring) - This doesn't show up in the report

Periodic copy (pruning) - This shows up in the report

Thanks for the work or love what this script does.  It took a bit to test but hopefully this helps out in some way.

**Comment by marcohorstmann** [comment]
Hi @DoMeLater,
please try the development branch. I added support for Immediate copy to the development branch.
URL: https://github.com/marcohorstmann/MyVeeamReport/tree/development

Please give me feedback if it works. I only have v12 in my lab so I cannot test it with v11.

**Comment by DoMeLater** [comment]
That worked great on Veeam 11!!!  I'm going to test with version 12 now.  Thanks much.

**Comment by DoMeLater** [comment]
It worked for version 12 as well nice!!!  

Issues with 24 hour time frame for the below:

- Successful Backup copy task
- Successful Backup copy sessions
- Backup copy task with warnings or failures
- Backup copy sessions with warnings or failures
- Backup copy tasks
- Backup copy sessions

24 hour time frame is good for:

- Successful Backup tasks
- Successfull Backup sessions
- Backup Sessions with Warnings or Failures
- Backup Tasks
- Backup Sessions
- and all the above info

I'm going to check your config file to see if I missed something.

**Comment by marcohorstmann** [comment]
![image](https://user-images.githubusercontent.com/20782695/220372994-c3d8d1aa-01b8-4abb-ae0b-d3ef1b68f09c.png)
This is how it looks in my lab. Reportmode is set to 24

**Comment by DoMeLater** [comment]
Any debug mode I can send you?  Or can I get an email so I can send a teams link and I can show you what it is doing remotely?

Thanks

**Comment by DoMeLater** [comment]
I manually copy the main script and config script to a folder and run it.  Just wanted to add this for troubleshooting.

**Comment by marcohorstmann** [comment]
There is no debug mode I'm aware of. You can send me a teams message. marco.horstmann(ät)veeam.com.

**Comment by marcohorstmann** [comment]
Thx to @DoMeLater for troubleshooting. Issue was fixed even before it went to the main branch.
